Pzcfg/padding update
glideapps/glide-data-grid pull request #167
Opened 2022-02-10 23:43 UTC by pzcfg

Currently the `paddingBottom` and `paddingRight` values don't update until you interact with the grid.

https://user-images.githubusercontent.com/94077014/153515433-a32f2355-91d7-4cb8-8d77-e960c129d831.mp4

This fixes that by calling `onScroll` whenever `paddingBottom` or `paddingRight` change

https://user-images.githubusercontent.com/94077014/153515458-9d13fa6a-9ad6-43a6-bf44-09f99db7cd66.mp4

I did notice that when this value is changing rapidly the width/height of the cells seems to briefly change. Not sure what is causing that

https://user-images.githubusercontent.com/94077014/153515561-204abf3b-cb2c-435f-b5ea-4ddb57c7d812.mp4

2022-02-11 14:56 UTC, ivoelbert commented
Great catch! I'll look into this a bit more. Usually having effects with "fake" dependencies (paddingX is not used in that effect, we just want the re render) is asking for trouble. We're very guilty of that, as well.

Thanks for reporting, and double thanks for sending a PR.

2022-02-11 16:18 UTC, jassmith commented
I suspect the jitter is 100% due to onScroll not forcing things to draw unblitted. The blitting is thus stretched.

2022-02-19 23:27 UTC, jassmith commented
Okay I spent more time digging into this. The fluttering is due to a desync between the DOM element resizing and the redraw happening. I am honestly not entirely sure how to fix this.

2022-02-19 23:52 UTC, jassmith commented
Okay I figured it out. This will require a lot of testing because it fundamentally changes how we size the canvas. https://github.com/glideapps/glide-data-grid/tree/fix-padding-resize Give it a try see if you like the solution and consider including it in your branch.

2022-02-20 18:23 UTC, jassmith requested changes
This PR needs to incorporate some version of the modification I made in the demo branch + some relatively extensive testing of different embedding scenarios to ensure behavior remains the same.

2022-02-22 06:37 UTC, jassmith commented
Hey amigo, I'd really like to bring this in to 3.4.0 but if I just merge my branch you wont get the credit you deserve. I'd love if you took a moment to check out what can be done here.

2022-03-06 00:08 UTC, jassmith commented
Fixed in 3.4.0

2022-03-06 00:08 UTC, closed without merging