Add API for smooth scrolling
glideapps/glide-data-grid pull request #25
Opened 2021-02-26 13:13 UTC by chkn

Set `smoothScrollX` or `smoothScrollY` to `true` on `DataEditor` to have smooth scrolling on the respective axis(es).

Under the hood this has the following effects:

- Setting `smoothScrollX` or `smoothScrollY` to `true` on `GridScroller`, which causes
       `onVisibleRegionChanged` to fire with more granularity, passing
       `tx` and/or `ty` arguments as appropriate.

- Those are passed into `translateX` and `translateY` props on the data grid
       to specify a pixel translation on top of the cellXOffset/cellYOffset

If you don't do the above, it should work exactly as before, with the minor difference that `scrollLeft` is now clamped to be >= 0 in `ScrollRegion` update callback.

2021-02-26 13:15 UTC, chkn commented
@jassmith I think this puppy is ready for a look.

2021-02-28 19:59 UTC, jassmith commented
![image](https://user-images.githubusercontent.com/30443/109431627-56ae2d00-79bc-11eb-8861-61113941ae5a.png)
Bottom line still goes AWOL when scrolling down, make sure you test on a non-retina device.

2021-02-28 19:59 UTC, jassmith requested changes
See earlier comment

2021-03-01 15:46 UTC, chkn commented
@jassmith  Good catch! Tested on Windows and fixed that and another issue as well.

2021-03-01 22:27 UTC, merged