Update checkbox size to be proportional to cell height
glideapps/glide-data-grid pull request #504
Opened 2022-09-22 10:09 UTC by frankagathos

When updating row height the checkbox size doesn't update. E.g. decreasing the cell height causes the checkbox to cover other cells.

2022-09-22 16:05 UTC, jassmith commented
Thank you so much for this PR, I will get to it as soon as possible.

2022-09-25 04:00 UTC, jassmith requested changes
This doesn't handle making sure the click area is appropriately changed to match.

2022-09-25 10:49 UTC, frankagathos commented on packages/core/src/data-grid/data-grid-lib.ts
> +    const checkBoxWidth = height / 1.888_888_888_888_889; // checkbox width proportional to cell height
Reduced to 9 decimals.

2022-09-30 03:46 UTC, merged

2023-01-30 01:25 UTC, anovazzi1 commented
Is there a way to toggle this option on DataGrid props? because now the check get's really ugly when the row height gets bigger, It would be perfect if it's size didn't change after row resize

2023-01-30 02:00 UTC, jassmith commented
I added that in 5.2.2 already :)

2023-01-30 20:23 UTC, anovazzi1 commented
awesome, how can i use it from package.json, i see the npm is in version 5.2.1

2023-01-30 20:33 UTC, jassmith commented
5.2.2-beta2 has been published, you can play with it there.

2023-01-30 21:03 UTC, anovazzi1 commented
thanks