An attempt at in-memory undo/redo support
glideapps/glide-data-grid pull request #556
Opened 2022-11-17 23:10 UTC by aaronSig

This add a hook & storybook example showing in-memory undo and redo support. It works by wrapping the `getCellContent` and `setCellValue` functions so it can fetch a cell before it is updated and replay any updates back. 

Open to feedback and no pressure to merge if you don't think this is in scope. It may be better done in the datasource.

2022-11-17 23:50 UTC, jassmith requested changes
You are right about moving this to the source package. Other than that this looks fine to me. We can work on improvements incrementally.

2022-11-17 23:50 UTC, jassmith commented on packages/core/src/data-editor/stories/data-editor-beautiful.stories.tsx
> +(UnevenRows as any).parameters = {
Wrong story :)

2022-11-18 09:10 UTC, aaronSig commented on packages/core/src/data-editor/stories/data-editor-beautiful.stories.tsx
> +(UnevenRows as any).parameters = {
Ah - thanks for catching.

2022-11-18 09:48 UTC, aaronSig commented
That's great! 

I've fixed up that typo & moved the hook down into the source package. I needed some of the utils for the story so I've moved those as well.

2022-11-18 23:24 UTC, jassmith approved these changes

2022-11-19 01:45 UTC, merged

2023-04-09 22:48 UTC, tortarino commented
Hello,

Thanks to both of you for all the great work!

It seems the undo/redo feature has not made it to the npm repository:
https://www.npmjs.com/package/@glideapps/glide-data-grid-source?activeTab=code

Am I missing something?

Thanks

2023-04-12 10:45 UTC, aaronSig commented
No, it doesn't look like it's in npm. 

The undo/redo hook is all self contained in one file though `packages/source/src/use-undo-redo.ts`

You could get by just copying that into your project.